apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-deployment
  minReplicas: 4
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
