apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    name: MysqlDB-Service
    app: Login-Apppication
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: MysqlDB-Pod
    app: Login-Apppication
